// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSKT31-hephx_En4q6RV1SIk366rzmlY',
    appId: '1:687128414189:web:90a555f8fa591b24b249e4',
    messagingSenderId: '687128414189',
    projectId: 'csgo-stats-ea61f',
    authDomain: 'csgo-stats-ea61f.firebaseapp.com',
    storageBucket: 'csgo-stats-ea61f.appspot.com',
    measurementId: 'G-1DDDT8K96M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqkAlGXjW9v5cRFnIBlKQOGsWnYrR93k',
    appId: '1:687128414189:android:2653226fec55e742b249e4',
    messagingSenderId: '687128414189',
    projectId: 'csgo-stats-ea61f',
    storageBucket: 'csgo-stats-ea61f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDad5-Sy9-Xsz7aqQvpHHETHbBo7LDxADc',
    appId: '1:687128414189:ios:5aa216a57a699c71b249e4',
    messagingSenderId: '687128414189',
    projectId: 'csgo-stats-ea61f',
    storageBucket: 'csgo-stats-ea61f.appspot.com',
    iosClientId: '687128414189-f1pgfef3vj25o5sth2pd0rlth36l4j5u.apps.googleusercontent.com',
    iosBundleId: 'com.vanzylarno.csgoStats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDad5-Sy9-Xsz7aqQvpHHETHbBo7LDxADc',
    appId: '1:687128414189:ios:8ffa62ec99049eebb249e4',
    messagingSenderId: '687128414189',
    projectId: 'csgo-stats-ea61f',
    storageBucket: 'csgo-stats-ea61f.appspot.com',
    iosClientId: '687128414189-4ke0e9nb6dn769olmdfi39p87ma31coc.apps.googleusercontent.com',
    iosBundleId: 'com.vanzylarno.csgoStats.RunnerTests',
  );
}
